ALTER PROC [dbo].[SP_CHECKTT_MAVT]
@MAVT nchar(4)
AS
BEGIN
	IF EXISTS(SELECT 1 
			  FROM (SELECT MAVT FROM Vattu) VT  
			  WHERE VT.MAVT = @MAVT  AND (EXISTS(SELECT 1 FROM CTPN WHERE CTPN.MAVT = VT.MAVT) OR EXISTS(SELECT 1 FROM CTPX WHERE CTPX.MAVT = VT.MAVT) 
					OR EXISTS(SELECT 1 FROM CTDDH WHERE CTDDH.MAVT = VT.MAVT)))
			RETURN 1; -- Mã Vattu đang dùng ở phân mảnh hiện tại
	ELSE IF EXISTS(SELECT 1
				   FROM (SELECT MAVT FROM Vattu) VT  
				   WHERE VT.MAVT = @MAVT AND (EXISTS(SELECT 1 FROM LINK1.QLVT_DATHANG.dbo.CTPN PN WHERE PN.MAVT = VT.MAVT) OR EXISTS(SELECT MAPX FROM LINK1.QLVT_DATHANG.dbo.CTPX PX WHERE PX.MAVT = VT.MAVT) 
						OR EXISTS(SELECT MasoDDH FROM LINK1.QLVT_DATHANG.dbo.CTDDH DH WHERE DH.MAVT = VT.MAVT)))
			RETURN 2; -- Mã Vattu đang dùng ở phân mảnh khác
	RETURN 0; -- Không dùng
END
