ALTER PROC [dbo].[sp_PhieuNvLapTrongNamTheoLoai]
@LOAI CHAR, @NAM INT
AS
IF (@LOAI = 'N')
	SELECT PS.PHIEU, NGAY, TENVT, SOLUONG, DONGIA, 
	   TRI_GIA = SOLUONG * DONGIA, NV.MANV, NV.HOTEN
	FROM (SELECT PHIEU = MAPN, NGAY, MANV
			FROM dbo.PhieuNhap 
			WHERE YEAR(NGAY)=@NAM) PS,
			CTPN CT, VATTU VT,
		(SELECT MANV, HOTEN=HO + ' ' + TEN
		FROM dbo.NhanVien) NV
		WHERE PS.PHIEU=CT.MAPN AND CT.MAVT=VT.MAVT AND PS.MANV = NV.MANV
	ORDER BY NGAY
ELSE
	SELECT PS.PHIEU, NGAY, TENVT, SOLUONG, DONGIA, 
	   TRI_GIA = SOLUONG * DONGIA, NV.MANV, NV.HOTEN
	FROM (SELECT PHIEU = MAPX, NGAY, MANV
			FROM dbo.PhieuXuat 
			WHERE YEAR(NGAY)=@NAM) PS,
			CTPX CT, VATTU VT,
		(SELECT MANV, HOTEN=HO + ' ' + TEN
		FROM dbo.NhanVien) NV
		WHERE PS.PHIEU=CT.MAPX AND CT.MAVT=VT.MAVT AND PS.MANV = NV.MANV
	ORDER BY NGAY
