ALTER PROC [dbo].[SP_REPORTChitiethangNhapXuat_NV]
@ROLE NVARCHAR(8),@LOAI NVARCHAR(4), @THANGFROM INT, @NAMFROM INT, @THANGTO INT, @NAMTO INT
AS
BEGIN
	IF (@ROLE = 'CONGTY')
	BEGIN
		IF (@LOAI = 'NHAP')
		BEGIN
			SELECT NGAY,TENVT, SOLUONG, TRIGIA=SOLUONG * DONGIA
			FROM (SELECT MAVT, TENVT FROM VATTU) VATTU,
				((SELECT MAPN, NGAY FROM PhieuNhap WHERE (YEAR(NGAY) >= @NAMFROM AND MONTH(NGAY)>=@THANGFROM) AND (YEAR(NGAY) <= @NAMTO AND MONTH(NGAY)<=@THANGTO))
				UNION
				(SELECT MAPN,NGAY FROM LINK1.QLVT_DATHANG.dbo.PhieuNhap WHERE (YEAR(NGAY) >= @NAMFROM AND MONTH(NGAY)>=@THANGFROM) AND (YEAR(NGAY) <= @NAMTO AND MONTH(NGAY)<=@THANGTO))) PN,
				(SELECT * FROM CTPN UNION SELECT * FROM LINK1.QLVT_DATHANG.dbo.CTPN) CT
			WHERE (VATTU.MAVT = CT.MAVT) AND(PN.MAPN=CT.MAPN)
			ORDER BY NGAY 
		END
		ELSE
		BEGIN
			SELECT NGAY,TENVT, SOLUONG, TRIGIA=SOLUONG * DONGIA
			FROM (SELECT MAVT, TENVT FROM VATTU) VATTU,
				((SELECT MAPX,NGAY FROM PhieuXuat WHERE (YEAR(NGAY) >= @NAMFROM AND MONTH(NGAY)>=@THANGFROM) AND (YEAR(NGAY) <= @NAMTO AND MONTH(NGAY)<=@THANGTO)) 
				UNION
				(SELECT MAPX,NGAY FROM LINK1.QLVT_DATHANG.dbo.PhieuXuat WHERE (YEAR(NGAY) >= @NAMFROM AND MONTH(NGAY)>=@THANGFROM) AND (YEAR(NGAY) <= @NAMTO AND MONTH(NGAY)<=@THANGTO))) PX,
				(SELECT * FROM CTPX UNION SELECT * FROM LINK1.QLVT_DATHANG.dbo.CTPX) CT
			WHERE (VATTU.MAVT = CT.MAVT) AND(PX.MAPX=CT.MAPX)
			ORDER BY NGAY 
		END
	END
	ELSE
	BEGIN
		IF (@LOAI = 'NHAP')
		BEGIN
			SELECT NGAY,TENVT, SOLUONG, TRIGIA=SOLUONG * DONGIA
			FROM CTPN CT, 
				(SELECT MAVT, TENVT FROM VATTU) VATTU,
				(SELECT MAPN,NGAY FROM PhieuNhap WHERE (YEAR(NGAY) >= @NAMFROM AND MONTH(NGAY)>=@THANGFROM) AND (YEAR(NGAY) <= @NAMTO AND MONTH(NGAY)<=@THANGTO)) PN
			WHERE (VATTU.MAVT = CT.MAVT) AND(PN.MAPN=CT.MAPN) 
		END
		ELSE
		BEGIN
			SELECT NGAY,TENVT, SOLUONG, TRIGIA=SOLUONG * DONGIA
			FROM CTPX CT, 
			(SELECT MAVT, TENVT FROM VATTU) VATTU,
			(SELECT MAPX,NGAY FROM PhieuXuat WHERE (YEAR(NGAY) >= @NAMFROM AND MONTH(NGAY)>=@THANGFROM) AND (YEAR(NGAY) <= @NAMTO AND MONTH(NGAY)<=@THANGTO)) PX
			WHERE (VATTU.MAVT = CT.MAVT) AND(PX.MAPX=CT.MAPX) 
		END
	END
END
