// TỔNG HỢP NHẬP XUẤT
ALTER PROC [dbo].[SP_REPORTTonghopNhapXuat_NV]
	@NGAYBD date, @NGAYKT date
AS
BEGIN
	SET NOCOUNT ON;
		IF 1=0 BEGIN
			SET FMTONLY OFF
		END
		SELECT	PN.NGAY,
				NHAP = SUM(CTPN.SOLUONG * CTPN.DONGIA), 
				TYLENHAP = (SUM(CTPN.SOLUONG * CTPN.DONGIA) / (SELECT SUM(SOLUONG*DONGIA) FROM CTPN INNER JOIN PhieuNhap ON CTPN.MAPN=PhieuNhap.MAPN WHERE NGAY BETWEEN @NGAYBD AND @NGAYKT)) INTO #PhieuNhapTemp
		FROM PhieuNhap AS PN
			INNER JOIN (SELECT * FROM CTPN) AS CTPN 
			ON PN.MAPN = CTPN.MAPN
		WHERE NGAY BETWEEN @NGAYBD AND @NGAYKT
		GROUP BY PN.NGAY

		SELECT	PX.NGAY,
				XUAT = SUM(CTPX.SOLUONG * CTPX.DONGIA),
				TYLEXUAT = (SUM(CTPX.SOLUONG * CTPX.DONGIA) / (SELECT SUM(SOLUONG*DONGIA) FROM CTPX INNER JOIN PhieuXuat ON CTPX.MAPX=PhieuXuat.MAPX WHERE NGAY BETWEEN @NGAYBD AND @NGAYKT))  INTO #PhieuXuatTemp
		FROM PhieuXuat AS PX
			INNER JOIN (SELECT * FROM CTPX) AS CTPX 
			ON PX.MAPX = CTPX.MAPX
		WHERE NGAY BETWEEN @NGAYBD AND @NGAYKT
		GROUP BY PX.NGAY				

		SELECT 
		ISNULL(PN.NGAY, PX.NGAY) AS NGAY, --
		ISNULL(PN.NHAP, 0) AS NHAP,
		ISNULL(PN.TYLENHAP, 0) AS TYLENHAP,
		ISNULL(PX.XUAT, 0) AS XUAT,
		ISNULL(PX.TYLEXUAT, 0) AS TYLEXUAT
		FROM #PhieuNhapTemp AS PN
		FULL JOIN #PhieuXuatTemp AS PX
		ON PN.NGAY = PX.NGAY
		ORDER BY NGAY
END
