ALTER PROCEDURE [dbo].[SP_UpdateSLVatTu]
@MAVT nchar(4),
@SOLUONG int,
@TYPE NVARCHAR(6)
AS
BEGIN
	IF(@TYPE = 'IMPORT')
	BEGIN
		IF EXISTS(SELECT MAVT FROM dbo.CTPN WHERE dbo.CTPN.MAVT =  @MAVT)
			BEGIN
				UPDATE dbo.Vattu SET SOLUONGTON = SOLUONGTON + @SOLUONG WHERE MAVT= @MAVT
				RETURN 1
			END
			ELSE
				RETURN 0
	END

	IF(@TYPE = 'EXPORT')
	BEGIN
		IF EXISTS(SELECT MAVT FROM dbo.CTPX WHERE dbo.CTPX.MAVT =  @MAVT)
			BEGIN
				UPDATE dbo.Vattu SET SOLUONGTON = SOLUONGTON - @SOLUONG WHERE MAVT= @MAVT
				RETURN 1
			END
			ELSE
				RETURN 0
	END
END
