ALTER PROC [dbo].[Xoa_Login]
@USRNAME VARCHAR(50)
AS
DECLARE @LGNAME VARCHAR(50)
IF EXISTS (SELECT SUSER_SNAME(sid) FROM sys.sysusers WHERE name = CAST(@USRNAME AS NVARCHAR))
BEGIN
	SET @LGNAME = CAST((SELECT SUSER_SNAME(sid) FROM sys.sysusers WHERE name = CAST(@USRNAME AS NVARCHAR)) AS VARCHAR(50))
	EXEC SP_DROPUSER @USRNAME
	EXEC SP_DROPLOGIN @LGNAME
END
